### PR TITLE
Add student

### PR DESCRIPTION
**Pull request by srevian**

### CODE REVIEW

**Comment by avistein** [comment]
Provide screenshot here

**Comment by srevian** [comment]
addstudentui

**Comment by srevian** [comment]
addstudenrtui_2

**Comment by avistein** [comment]
Swap Current Semester and Academic Year

**Review by avistein — CHANGES_REQUESTED** [review]
Swap academic year and current semester

**Review by avistein — APPROVED** [review]

**Review by avistein — APPROVED** [review]

**Comment by avistein** [comment]
Are all ids provided for every textfields and comboboxes?

**Comment by avistein** [comment]
Open SceneBuilder -> Select an item -> Left Hand side code -> provide id to every items

ids should be like this - firstNameTextField,batchComboBox,disciplineComboBox etc.

**Also provide action for every ComboBox and the Submit button, for example action for batchComboBox should be handleBatchComboBoxAction, action for submit button should be handleSubmitButtonAction**

**Comment by srevian** [comment]
No, Not yet. So, I am providing it.

**Comment by srevian** [comment]
anything else ?

**Comment by srevian** [comment]
check it out

**Review by avistein — CHANGES_REQUESTED** [review]
Provide action too.Check last comment. Action only for ComboBoxes and Submit Button, nothing else.

**Review by avistein — APPROVED** [review]

**Pull request merged**
